"""baseline

Revision ID: 0001
Revises: (none)
Create Date: 2026-10-09 14:22:49.903957
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "app_settings",
        sa.Column("key", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("value", sa.JSON(), nullable=True),
        sa.Column("updated_by", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("updated_at", sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "event_log",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("session_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("team_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("actor", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("kind", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("created_at", sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("event_log", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_event_log_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_event_log_kind"), ["kind"], unique=False)
        batch_op.create_index(batch_op.f("ix_event_log_session_id"), ["session_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_event_log_team_id"), ["team_id"], unique=False)

    op.create_table(
        "game_sessions",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("seed", sa.Integer(), nullable=False),
        sa.Column("round2_mechanic", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("content_version", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("stage_index", sa.Integer(), nullable=False),
        sa.Column("stage_status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("stage_started_at", sqlmodel.sql.sqltypes.UTCDateTime(), nullable=True),
        sa.Column("elapsed_before_pause", sa.Float(), nullable=False),
        sa.Column("released", sa.JSON(), nullable=False),
        sa.Column("simulated_years", sa.Integer(), nullable=False),
        sa.Column("round2_granted", sa.Boolean(), nullable=False),
        sa.Column("options", sa.JSON(), server_default="{}", nullable=False),
        sa.Column("created_at", sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
        sa.Column("updated_at", sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "teams",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("session_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("payer_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("join_code", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("state", sa.JSON(), nullable=False),
        sa.Column("workspace", sa.JSON(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("updated_at", sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["game_sessions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("teams", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_teams_join_code"), ["join_code"], unique=True)
        batch_op.create_index(batch_op.f("ix_teams_session_id"), ["session_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("teams", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_teams_session_id"))
        batch_op.drop_index(batch_op.f("ix_teams_join_code"))

    op.drop_table("teams")
    op.drop_table("game_sessions")
    with op.batch_alter_table("event_log", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_event_log_team_id"))
        batch_op.drop_index(batch_op.f("ix_event_log_session_id"))
        batch_op.drop_index(batch_op.f("ix_event_log_kind"))
        batch_op.drop_index(batch_op.f("ix_event_log_created_at"))

    op.drop_table("event_log")
    op.drop_table("app_settings")
    # ### end Alembic commands ###
